import {
  Exercise,
  MuscleGroup,
  ExerciseType,
  ExerciseEquipment,
  ExerciseOwnership,
} from "./definitions";

const exercises: Exercise[] = [
  // 🏋️ Barbell Exercises
  {
    id: "ex-001",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Squat",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [
      MuscleGroup.Glutes,
      MuscleGroup.Hamstrings,
      MuscleGroup.Lower_Back,
    ],
    type: ExerciseType.Large,
  },
  {
    id: "ex-002",
    owner: ExerciseOwnership.BFit,
    name: "Deadlift",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Lower_Back,
    auxiliaryMuscles: [
      MuscleGroup.Glutes,
      MuscleGroup.Hamstrings,
      MuscleGroup.Traps,
    ],
    type: ExerciseType.Large,
  },
  {
    id: "ex-003",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Bench Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Front_Delts],
    type: ExerciseType.Large,
  },
  {
    id: "ex-004",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Overhead Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Upper_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-005",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Bent-over Row",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Lats, MuscleGroup.Biceps],
    type: ExerciseType.Medium,
  },

  // 💪 Dumbbell Exercises
  {
    id: "ex-006",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Bicep Curl",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-007",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Shoulder Press",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-008",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Lateral Raise",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Side_Delts,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-009",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Romanian Deadlift",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-010",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Incline Press",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },

  // 🔄 Machine Exercises
  {
    id: "ex-011",
    owner: ExerciseOwnership.BFit,
    name: "Leg Press",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-012",
    owner: ExerciseOwnership.BFit,
    name: "Seated Row Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-013",
    owner: ExerciseOwnership.BFit,
    name: "Chest Press Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-014",
    owner: ExerciseOwnership.BFit,
    name: "Leg Curl Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-015",
    owner: ExerciseOwnership.BFit,
    name: "Leg Extension Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [],
    type: ExerciseType.Medium,
  },

  // More exercises will be added here until we reach 300...
  {
    id: "ex-016",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Romanian Deadlift",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-017",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Front Squat",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-018",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Hip Thrust",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-019",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Shrugs",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Traps,
    auxiliaryMuscles: [MuscleGroup.Forearms],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-020",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Bent-Over Rows",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Lats, MuscleGroup.Rear_Delts],
    type: ExerciseType.Large,
  },
  {
    id: "ex-021",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Lateral Raise",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Side_Delts,
    auxiliaryMuscles: [MuscleGroup.Traps],
    type: ExerciseType.Small,
  },
  {
    id: "ex-022",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Rear Delt Fly",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back],
    type: ExerciseType.Small,
  },
  {
    id: "ex-023",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Bulgarian Split Squat",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-024",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Hammer Curl",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [MuscleGroup.Forearms],
    type: ExerciseType.Small,
  },
  {
    id: "ex-025",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Wrist Curls",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Forearms,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-026",
    owner: ExerciseOwnership.BFit,
    name: "Seated Leg Press",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-027",
    owner: ExerciseOwnership.BFit,
    name: "Seated Chest Press",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-028",
    owner: ExerciseOwnership.BFit,
    name: "Seated Shoulder Press Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Upper_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-029",
    owner: ExerciseOwnership.BFit,
    name: "Leg Curl Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes],
    type: ExerciseType.Small,
  },
  {
    id: "ex-030",
    owner: ExerciseOwnership.BFit,
    name: "Seated Calf Raise Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Calves,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-031",
    owner: ExerciseOwnership.BFit,
    name: "Cable Face Pulls",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back, MuscleGroup.Traps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-032",
    owner: ExerciseOwnership.BFit,
    name: "Cable Rope Triceps Pushdown",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-033",
    owner: ExerciseOwnership.BFit,
    name: "Cable Bicep Curls",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [MuscleGroup.Forearms],
    type: ExerciseType.Small,
  },
  {
    id: "ex-034",
    owner: ExerciseOwnership.BFit,
    name: "Cable Lat Pulldown",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Lats,
    auxiliaryMuscles: [MuscleGroup.Upper_Back, MuscleGroup.Biceps],
    type: ExerciseType.Large,
  },
  {
    id: "ex-035",
    owner: ExerciseOwnership.BFit,
    name: "Cable Glute Kickback",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-056",
    owner: ExerciseOwnership.BFit,
    name: "Smith Machine Squat",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-057",
    owner: ExerciseOwnership.BFit,
    name: "Smith Machine Shoulder Press",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-058",
    owner: ExerciseOwnership.BFit,
    name: "Smith Machine Deadlift",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-059",
    owner: ExerciseOwnership.BFit,
    name: "Smith Machine Calf Raise",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Calves,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-060",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Overhead Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Upper_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-061",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Pendlay Row",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Biceps, MuscleGroup.Lats],
    type: ExerciseType.Large,
  },
  {
    id: "ex-062",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Front Squat",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-063",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Good Morning",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-064",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Bulgarian Split Squat",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-065",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Lateral Raises",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Side_Delts,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-066",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Arnold Press",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-067",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Farmer’s Walk",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Forearms,
    auxiliaryMuscles: [MuscleGroup.Traps, MuscleGroup.Core],
    type: ExerciseType.Large,
  },
  {
    id: "ex-068",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Reverse Fly",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-069",
    owner: ExerciseOwnership.BFit,
    name: "Cable Face Pull",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back, MuscleGroup.Traps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-070",
    owner: ExerciseOwnership.BFit,
    name: "Cable Rope Triceps Pushdown",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-071",
    owner: ExerciseOwnership.BFit,
    name: "Cable Lateral Raises",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Side_Delts,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-072",
    owner: ExerciseOwnership.BFit,
    name: "Cable Chest Fly",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-073",
    owner: ExerciseOwnership.BFit,
    name: "Cable Lat Pulldown",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Lats,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Large,
  },
  {
    id: "ex-074",
    owner: ExerciseOwnership.BFit,
    name: "Machine Seated Calf Raise",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Calves,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-075",
    owner: ExerciseOwnership.BFit,
    name: "Machine Leg Curl",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-076",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Reverse Lunge",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-077",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Floor Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-078",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Hack Squat",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-079",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Zercher Squat",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Core],
    type: ExerciseType.Large,
  },
  {
    id: "ex-080",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Snatch",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings, MuscleGroup.Traps],
    type: ExerciseType.Large,
  },

  // 💪 Dumbbell Exercises
  {
    id: "ex-081",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Goblet Squat",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-082",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Chest Fly",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-083",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Step-Up",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-084",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Zottman Curl",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [MuscleGroup.Forearms],
    type: ExerciseType.Small,
  },
  {
    id: "ex-085",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Reverse Lunge",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },

  // 🔄 Machine Exercises
  {
    id: "ex-086",
    owner: ExerciseOwnership.BFit,
    name: "Seated Hamstring Curl Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-087",
    owner: ExerciseOwnership.BFit,
    name: "Pec Deck Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-088",
    owner: ExerciseOwnership.BFit,
    name: "Leg Abduction Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Abductors,
    auxiliaryMuscles: [],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-089",
    owner: ExerciseOwnership.BFit,
    name: "Assisted Pull-Up Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Lats,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Large,
  },
  {
    id: "ex-090",
    owner: ExerciseOwnership.BFit,
    name: "Reverse Hyperextension Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Lower_Back,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },

  // 🔄 Cable Exercises
  {
    id: "ex-091",
    owner: ExerciseOwnership.BFit,
    name: "Cable Overhead Triceps Extension",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-092",
    owner: ExerciseOwnership.BFit,
    name: "Cable Reverse Fly",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-093",
    owner: ExerciseOwnership.BFit,
    name: "Cable Pull-Through",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-094",
    owner: ExerciseOwnership.BFit,
    name: "Cable Seated Row",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-095",
    owner: ExerciseOwnership.BFit,
    name: "Cable Side Bend",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Core,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-096",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Deficit Deadlift",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Lower_Back,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-097",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Box Squat",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-098",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Sumo Deadlift",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-099",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Clean and Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Traps, MuscleGroup.Hamstrings, MuscleGroup.Quads],
    type: ExerciseType.Large,
  },
  {
    id: "ex-100",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Close-Grip Bench Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [MuscleGroup.Chest, MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  
  // 💪 Dumbbell Exercises
  {
    id: "ex-101",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Goblet Lunge",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-102",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Lying Triceps Extension",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-103",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Side Lunge",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-104",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Snatch",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Quads, MuscleGroup.Hamstrings, MuscleGroup.Core],
    type: ExerciseType.Large,
  },
  {
    id: "ex-105",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Incline Curl",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  
  // 🔄 Machine Exercises
  {
    id: "ex-106",
    owner: ExerciseOwnership.BFit,
    name: "Machine Hack Squat",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-107",
    owner: ExerciseOwnership.BFit,
    name: "Machine Assisted Dips",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [MuscleGroup.Chest, MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-108",
    owner: ExerciseOwnership.BFit,
    name: "Machine Reverse Fly",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-109",
    owner: ExerciseOwnership.BFit,
    name: "Machine Hip Thrust",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-110",
    owner: ExerciseOwnership.BFit,
    name: "Machine Ab Crunch",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Core,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
];

export default exercises;
