import {
  Exercise,
  MuscleGroup,
  ExerciseType,
  ExerciseEquipment,
  ExerciseOwnership,
} from "./definitions";

const exercises: Exercise[] = [
  {
    id: "ex-001",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Squat",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [
      MuscleGroup.Glutes,
      MuscleGroup.Hamstrings,
      MuscleGroup.Lower_Back,
    ],
    type: ExerciseType.Large,
  },
  {
    id: "ex-002",
    owner: ExerciseOwnership.BFit,
    name: "Deadlift",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Lower_Back,
    auxiliaryMuscles: [
      MuscleGroup.Glutes,
      MuscleGroup.Hamstrings,
      MuscleGroup.Traps,
    ],
    type: ExerciseType.Large,
  },
  {
    id: "ex-003",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Bench Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Front_Delts],
    type: ExerciseType.Large,
  },
  {
    id: "ex-004",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Overhead Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Upper_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-005",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Bent-over Row",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Lats, MuscleGroup.Biceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-006",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Bicep Curl",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-007",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Shoulder Press",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-008",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Lateral Raise",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Side_Delts,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-009",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Romanian Deadlift",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-010",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Incline Press",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-011",
    owner: ExerciseOwnership.BFit,
    name: "Leg Press",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-012",
    owner: ExerciseOwnership.BFit,
    name: "Seated Row Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-013",
    owner: ExerciseOwnership.BFit,
    name: "Chest Press Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-014",
    owner: ExerciseOwnership.BFit,
    name: "Leg Curl Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-015",
    owner: ExerciseOwnership.BFit,
    name: "Leg Extension Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-016",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Romanian Deadlift",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-017",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Front Squat",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-018",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Hip Thrust",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-019",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Shrug",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Traps,
    auxiliaryMuscles: [MuscleGroup.Forearms],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-020",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Underhand Bent-over Row",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Lats, MuscleGroup.Rear_Delts],
    type: ExerciseType.Large,
  },
  {
    id: "ex-021",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Lateral Raise",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Side_Delts,
    auxiliaryMuscles: [MuscleGroup.Traps],
    type: ExerciseType.Small,
  },
  {
    id: "ex-022",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Rear Delt Fly",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back],
    type: ExerciseType.Small,
  },
  {
    id: "ex-023",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Bulgarian Split Squat",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-024",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Hammer Curl",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [MuscleGroup.Forearms],
    type: ExerciseType.Small,
  },
  {
    id: "ex-025",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Wrist Curl",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Forearms,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-026",
    owner: ExerciseOwnership.BFit,
    name: "Seated Leg Press",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-027",
    owner: ExerciseOwnership.BFit,
    name: "Seated Chest Press",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-028",
    owner: ExerciseOwnership.BFit,
    name: "Seated Shoulder Press Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Upper_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-029",
    owner: ExerciseOwnership.BFit,
    name: "Leg Curl Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes],
    type: ExerciseType.Small,
  },
  {
    id: "ex-030",
    owner: ExerciseOwnership.BFit,
    name: "Machine Seated Calf Raise",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Calves,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-031",
    owner: ExerciseOwnership.BFit,
    name: "Cable Face Pull",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back, MuscleGroup.Traps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-032",
    owner: ExerciseOwnership.BFit,
    name: "Cable Rope Triceps Pushdown",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-033",
    owner: ExerciseOwnership.BFit,
    name: "Cable Bicep Curl",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [MuscleGroup.Forearms],
    type: ExerciseType.Small,
  },
  {
    id: "ex-034",
    owner: ExerciseOwnership.BFit,
    name: "Cable Lat Pulldown",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Lats,
    auxiliaryMuscles: [MuscleGroup.Upper_Back, MuscleGroup.Biceps],
    type: ExerciseType.Large,
  },
  {
    id: "ex-035",
    owner: ExerciseOwnership.BFit,
    name: "Cable Glute Kickback",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-036",
    owner: ExerciseOwnership.BFit,
    name: "TRX Row",
    equipment: ExerciseEquipment.TRX,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Biceps, MuscleGroup.Rear_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-037",
    owner: ExerciseOwnership.BFit,
    name: "TRX Push-ups",
    equipment: ExerciseEquipment.TRX,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-038",
    owner: ExerciseOwnership.BFit,
    name: "TRX Single-Leg Squat",
    equipment: ExerciseEquipment.TRX,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-039",
    owner: ExerciseOwnership.BFit,
    name: "Trap Bar Deadlift",
    equipment: ExerciseEquipment.TrapBar,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-040",
    owner: ExerciseOwnership.BFit,
    name: "Trap Bar Shrugs",
    equipment: ExerciseEquipment.TrapBar,
    primaryMuscle: MuscleGroup.Traps,
    auxiliaryMuscles: [MuscleGroup.Forearms],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-041",
    owner: ExerciseOwnership.BFit,
    name: "EZ Bar Bicep Curl",
    equipment: ExerciseEquipment.EzBar,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [MuscleGroup.Forearms],
    type: ExerciseType.Small,
  },
  {
    id: "ex-042",
    owner: ExerciseOwnership.BFit,
    name: "EZ Bar Skull Crushers",
    equipment: ExerciseEquipment.EzBar,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-043",
    owner: ExerciseOwnership.BFit,
    name: "EZ Bar Reverse Curl",
    equipment: ExerciseEquipment.EzBar,
    primaryMuscle: MuscleGroup.Forearms,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Small,
  },
  {
    id: "ex-044",
    owner: ExerciseOwnership.BFit,
    name: "Kettlebell Goblet Squat",
    equipment: ExerciseEquipment.Kettlebells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-045",
    owner: ExerciseOwnership.BFit,
    name: "Kettlebell Swing",
    equipment: ExerciseEquipment.Kettlebells,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-046",
    owner: ExerciseOwnership.BFit,
    name: "Kettlebell Deadlift",
    equipment: ExerciseEquipment.Kettlebells,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-047",
    owner: ExerciseOwnership.BFit,
    name: "Kettlebell Clean & Press",
    equipment: ExerciseEquipment.Kettlebells,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Upper_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-048",
    owner: ExerciseOwnership.BFit,
    name: "Resistance Band Lateral Walk",
    equipment: ExerciseEquipment.ResistanceBands,
    primaryMuscle: MuscleGroup.Abductors,
    auxiliaryMuscles: [MuscleGroup.Glutes],
    type: ExerciseType.Small,
  },
  {
    id: "ex-049",
    owner: ExerciseOwnership.BFit,
    name: "Resistance Band Good Mornings",
    equipment: ExerciseEquipment.ResistanceBands,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-050",
    owner: ExerciseOwnership.BFit,
    name: "Resistance Band Face Pull",
    equipment: ExerciseEquipment.ResistanceBands,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back, MuscleGroup.Traps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-051",
    owner: ExerciseOwnership.BFit,
    name: "Machine Chest Fly",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-052",
    owner: ExerciseOwnership.BFit,
    name: "Machine Shoulder Press",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-053",
    owner: ExerciseOwnership.BFit,
    name: "Machine Leg Extension",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-054",
    owner: ExerciseOwnership.BFit,
    name: "Seated High Row Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Lats, MuscleGroup.Biceps],
    type: ExerciseType.Large,
  },
  {
    id: "ex-055",
    owner: ExerciseOwnership.BFit,
    name: "Machine Glute Bridge",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-056",
    owner: ExerciseOwnership.BFit,
    name: "Smith Machine Squat",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-057",
    owner: ExerciseOwnership.BFit,
    name: "Smith Machine Shoulder Press",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-058",
    owner: ExerciseOwnership.BFit,
    name: "Smith Machine Deadlift",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-059",
    owner: ExerciseOwnership.BFit,
    name: "Smith Machine Calf Raise",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Calves,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-060",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Overhead Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Upper_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-061",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Pendlay Row",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Biceps, MuscleGroup.Lats],
    type: ExerciseType.Large,
  },
  {
    id: "ex-062",
    owner: ExerciseOwnership.BFit,
    name: "Smithmachine Front Squat",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-063",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Good Morning",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-064",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Bulgarian Split Squat",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-065",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Lateral Raises",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Side_Delts,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-066",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Arnold Press",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Triceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-067",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Farmer’s Walk",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Forearms,
    auxiliaryMuscles: [MuscleGroup.Traps, MuscleGroup.Core],
    type: ExerciseType.Large,
  },
  {
    id: "ex-068",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Reverse Fly",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-069",
    owner: ExerciseOwnership.BFit,
    name: "TRX Face Pull",
    equipment: ExerciseEquipment.TRX,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back, MuscleGroup.Traps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-070",
    owner: ExerciseOwnership.BFit,
    name: "Cable Rope Triceps Pushdown",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-071",
    owner: ExerciseOwnership.BFit,
    name: "Cable Lateral Raises",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Side_Delts,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-072",
    owner: ExerciseOwnership.BFit,
    name: "Cable Chest Fly",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-073",
    owner: ExerciseOwnership.BFit,
    name: "Cable Lat Pulldown",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Lats,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Large,
  },
  {
    id: "ex-074",
    owner: ExerciseOwnership.BFit,
    name: "Machine Donkey Calf Raise",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Calves,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-075",
    owner: ExerciseOwnership.BFit,
    name: "Machine Leg Curl",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-076",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Reverse Lunge",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-077",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Floor Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-078",
    owner: ExerciseOwnership.BFit,
    name: "Smithmachine Bulgerian Squat",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-079",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Zercher Squat",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Core],
    type: ExerciseType.Large,
  },
  {
    id: "ex-080",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Snatch",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings, MuscleGroup.Traps],
    type: ExerciseType.Large,
  },
  {
    id: "ex-081",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Goblet Squat",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-082",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Chest Fly",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-083",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Step-Up",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-084",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Zottman Curl",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [MuscleGroup.Forearms],
    type: ExerciseType.Small,
  },
  {
    id: "ex-085",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Reverse Lunge",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-086",
    owner: ExerciseOwnership.BFit,
    name: "Seated Hamstring Curl Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-087",
    owner: ExerciseOwnership.BFit,
    name: "Pec Deck Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-088",
    owner: ExerciseOwnership.BFit,
    name: "Leg Abduction Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Abductors,
    auxiliaryMuscles: [],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-089",
    owner: ExerciseOwnership.BFit,
    name: "Assisted Pull-Up Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Lats,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Large,
  },
  {
    id: "ex-090",
    owner: ExerciseOwnership.BFit,
    name: "Reverse Hyperextension Machine",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Lower_Back,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-091",
    owner: ExerciseOwnership.BFit,
    name: "Cable Overhead Triceps Extension",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-092",
    owner: ExerciseOwnership.BFit,
    name: "Cable Reverse Fly",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-093",
    owner: ExerciseOwnership.BFit,
    name: "Cable Pull-Through",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-094",
    owner: ExerciseOwnership.BFit,
    name: "Cable Seated Row",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-095",
    owner: ExerciseOwnership.BFit,
    name: "Cable Side Bend",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Core,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-096",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Deficit Deadlift",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Lower_Back,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-097",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Box Squat",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-098",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Sumo Deadlift",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-099",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Clean and Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [MuscleGroup.Traps, MuscleGroup.Hamstrings, MuscleGroup.Quads],
    type: ExerciseType.Large,
  },
  {
    id: "ex-100",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Close-Grip Bench Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [MuscleGroup.Chest, MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-101",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Goblet Lunge",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-102",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Lying Triceps Extension",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-103",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Side Lunge",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-104",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Snatch",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Quads, MuscleGroup.Hamstrings, MuscleGroup.Core],
    type: ExerciseType.Large,
  },
  {
    id: "ex-105",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Incline Curl",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-106",
    owner: ExerciseOwnership.BFit,
    name: "Machine Hack Squat",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-107",
    owner: ExerciseOwnership.BFit,
    name: "Machine Assisted Dips",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [MuscleGroup.Chest, MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-108",
    owner: ExerciseOwnership.BFit,
    name: "Machine Reverse Fly",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Upper_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-109",
    owner: ExerciseOwnership.BFit,
    name: "Machine Hip Thrust",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings],
    type: ExerciseType.Large,
  },
  {
    id: "ex-110",
    owner: ExerciseOwnership.BFit,
    name: "Machine Ab Crunch",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Core,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-111",
    owner: ExerciseOwnership.BFit,
    name: "Assisted Pull-Up",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Lats,
    auxiliaryMuscles: [MuscleGroup.Biceps, MuscleGroup.Upper_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-112",
    owner: ExerciseOwnership.BFit,
    name: "Smithmachine Hip Thrust",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings, MuscleGroup.Core],
    type: ExerciseType.Large,
  },
  {
    id: "ex-114",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Pullover",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Lats,
    auxiliaryMuscles: [MuscleGroup.Chest, MuscleGroup.Core],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-115",
    owner: ExerciseOwnership.BFit,
    name: "Machine Lateral Raise",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Side_Delts,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-116",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Front Raise",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Front_Delts,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-117",
    owner: ExerciseOwnership.BFit,
    name: "Cable Wide Seated Row",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Lats, MuscleGroup.Biceps],
    type: ExerciseType.Large,
  },
  {
    id: "ex-118",
    owner: ExerciseOwnership.BFit,
    name: "EZ Bar Skullcrusher",
    equipment: ExerciseEquipment.EzBar,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-119",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Seated Hammer Curl",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Biceps,
    auxiliaryMuscles: [MuscleGroup.Forearms],
    type: ExerciseType.Small,
  },
  {
    id: "ex-120",
    owner: ExerciseOwnership.BFit,
    name: "Smith Machine Row",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Lats,
    auxiliaryMuscles: [MuscleGroup.Biceps, MuscleGroup.Upper_Back],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-121",
    owner: ExerciseOwnership.BFit,
    name: "Trap Bar Deficit Deadlift",
    equipment: ExerciseEquipment.TrapBar,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-122",
    owner: ExerciseOwnership.BFit,
    name: "TRX Single Hand Row",
    equipment: ExerciseEquipment.TRX,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Biceps, MuscleGroup.Lats],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-123",
    owner: ExerciseOwnership.BFit,
    name: "Kettlebell Swing",
    equipment: ExerciseEquipment.Kettlebells,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings, MuscleGroup.Core],
    type: ExerciseType.Large,
  },
  {
    id: "ex-124",
    owner: ExerciseOwnership.BFit,
    name: "Resistance Band Chest Fly",
    equipment: ExerciseEquipment.ResistanceBands,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-125",
    owner: ExerciseOwnership.BFit,
    name: "Bodyweight Step-Up",
    equipment: ExerciseEquipment.Bodyweight,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-126",
    owner: ExerciseOwnership.BFit,
    name: "Machine Single Leg Calf Raise",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Calves,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-127",
    owner: ExerciseOwnership.BFit,
    name: "Kettlebell Romanian Deadlift",
    equipment: ExerciseEquipment.Kettlebells,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-128",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Shrug",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Traps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-129",
    owner: ExerciseOwnership.BFit,
    name: "Cable Woodchopper",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Core,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-120",
    owner: ExerciseOwnership.BFit,
    name: "TRX Pike",
    equipment: ExerciseEquipment.TRX,
    primaryMuscle: MuscleGroup.Core,
    auxiliaryMuscles: [MuscleGroup.Front_Delts],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-129",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Reverse Lunge",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-130",
    owner: ExerciseOwnership.BFit,
    name: "Dumbbell Pullover",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Lats,
    auxiliaryMuscles: [MuscleGroup.Chest, MuscleGroup.Core],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-131",
    owner: ExerciseOwnership.BFit,
    name: "TRX Inverted Row",
    equipment: ExerciseEquipment.TRX,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Biceps, MuscleGroup.Core],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-132",
    owner: ExerciseOwnership.BFit,
    name: "Kettlebell Sumo Squat",
    equipment: ExerciseEquipment.Kettlebells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Core],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-133",
    owner: ExerciseOwnership.BFit,
    name: "Single Hand Cable Face Pull",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Traps, MuscleGroup.Upper_Back],
    type: ExerciseType.Small,
  },
  {
    id: "ex-134",
    owner: ExerciseOwnership.BFit,
    name: "Resistance Band Glute Kickback",
    equipment: ExerciseEquipment.ResistanceBands,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-135",
    owner: ExerciseOwnership.BFit,
    name: "EZ Bar Skull Crushers",
    equipment: ExerciseEquipment.EzBar,
    primaryMuscle: MuscleGroup.Triceps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-136",
    owner: ExerciseOwnership.BFit,
    name: "Smith Machine Standing Calf Raise",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Calves,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-137",
    owner: ExerciseOwnership.BFit,
    name: "Trap Bar Romanian Deadlift",
    equipment: ExerciseEquipment.TrapBar,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Lower_Back],
    type: ExerciseType.Large,
  },
  {
    id: "ex-138",
    owner: ExerciseOwnership.BFit,
    name: "Bodyweight Wall Sit",
    equipment: ExerciseEquipment.Bodyweight,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-139",
    owner: ExerciseOwnership.BFit,
    name: "Smithmachine Zercher Squat",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Core],
    type: ExerciseType.Large,
  },
  {
    id: "ex-140",
    owner: ExerciseOwnership.BFit,
    name: "Cable Hip Abduction",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Abductors,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-142",
    owner: ExerciseOwnership.BFit,
    name: "Reverse Grip Lat Pulldown",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Lats,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-143",
    owner: ExerciseOwnership.BFit,
    name: "Chest-Supported Dumbbell Row",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Rear_Delts, MuscleGroup.Biceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-144",
    owner: ExerciseOwnership.BFit,
    name: "Single-Arm Cable Lateral Raise",
    equipment: ExerciseEquipment.Cable,
    primaryMuscle: MuscleGroup.Side_Delts,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-145",
    owner: ExerciseOwnership.BFit,
    name: "Barbell Floor Press",
    equipment: ExerciseEquipment.Barbell,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-146",
    owner: ExerciseOwnership.BFit,
    name: "Banded Glute Bridge",
    equipment: ExerciseEquipment.ResistanceBands,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-147",
    owner: ExerciseOwnership.BFit,
    name: "Bodyweight Archer Push-Up",
    equipment: ExerciseEquipment.Bodyweight,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Triceps, MuscleGroup.Core],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-148",
    owner: ExerciseOwnership.BFit,
    name: "EZ Bar Reverse Curl",
    equipment: ExerciseEquipment.EzBar,
    primaryMuscle: MuscleGroup.Forearms,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Small,
  },
  {
    id: "ex-150",
    owner: ExerciseOwnership.BFit,
    name: "TRX Single Hand Inverted Row",
    equipment: ExerciseEquipment.TRX,
    primaryMuscle: MuscleGroup.Upper_Back,
    auxiliaryMuscles: [MuscleGroup.Biceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-151",
    owner: ExerciseOwnership.BFit,
    name: "Machine Standing Calf Raise",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Calves,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-152",
    owner: ExerciseOwnership.BFit,
    name: "Smith Machine Shrug",
    equipment: ExerciseEquipment.SmithMachine,
    primaryMuscle: MuscleGroup.Traps,
    auxiliaryMuscles: [],
    type: ExerciseType.Small,
  },
  {
    id: "ex-153",
    owner: ExerciseOwnership.BFit,
    name: "Single Leg Kettlebell Goblet Squat",
    equipment: ExerciseEquipment.Kettlebells,
    primaryMuscle: MuscleGroup.Quads,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Core],
    type: ExerciseType.Large,
  },
  {
    id: "ex-154",
    owner: ExerciseOwnership.BFit,
    name: "Single Hand Resistance Band Face Pull",
    equipment: ExerciseEquipment.ResistanceBands,
    primaryMuscle: MuscleGroup.Rear_Delts,
    auxiliaryMuscles: [MuscleGroup.Traps],
    type: ExerciseType.Small,
  },
  {
    id: "ex-155",
    owner: ExerciseOwnership.BFit,
    name: "Glute Bridge",
    equipment: ExerciseEquipment.Bodyweight,
    primaryMuscle: MuscleGroup.Glutes,
    auxiliaryMuscles: [MuscleGroup.Hamstrings, MuscleGroup.Core],
    type: ExerciseType.Large,
  },
  {
    id: "ex-156",
    owner: ExerciseOwnership.BFit,
    name: "Incline Machine Chest Press",
    equipment: ExerciseEquipment.Machine,
    primaryMuscle: MuscleGroup.Chest,
    auxiliaryMuscles: [MuscleGroup.Front_Delts, MuscleGroup.Triceps],
    type: ExerciseType.Medium,
  },
  {
    id: "ex-157",
    owner: ExerciseOwnership.BFit,
    name: "Romanian Deadlift Single Leg Dumbbell",
    equipment: ExerciseEquipment.Dumbbells,
    primaryMuscle: MuscleGroup.Hamstrings,
    auxiliaryMuscles: [MuscleGroup.Glutes, MuscleGroup.Core],
    type: ExerciseType.Medium,
  },
];

export default exercises;
